/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import java.awt.FlowLayout;
import java.util.*;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.*;
import javax.swing.JScrollPane;

/**
 *
 * @author Zeyad
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage
     */
    private String CurUserName;
    public AdminPage(String UserName) {
        initComponents();
        CurUserName=UserName;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        AllBookButton = new javax.swing.JButton();
        AllUserButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SendMessage = new javax.swing.JButton();
        BackToLogin_Button = new javax.swing.JButton();
        SendMoney_Button = new javax.swing.JButton();

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 153));

        AllBookButton.setBackground(new java.awt.Color(153, 255, 0));
        AllBookButton.setText("AllBook");
        AllBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllBookButtonActionPerformed(evt);
            }
        });

        AllUserButton.setBackground(new java.awt.Color(153, 255, 51));
        AllUserButton.setText("AllUser");
        AllUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllUserButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel1.setText("AdminPage");

        SendMessage.setBackground(new java.awt.Color(102, 255, 0));
        SendMessage.setText("SendMessage");
        SendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendMessageActionPerformed(evt);
            }
        });

        BackToLogin_Button.setBackground(new java.awt.Color(0, 255, 255));
        BackToLogin_Button.setText("BackToLogin");
        BackToLogin_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToLogin_ButtonActionPerformed(evt);
            }
        });

        SendMoney_Button.setBackground(new java.awt.Color(102, 255, 51));
        SendMoney_Button.setText("SendMoney");
        SendMoney_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendMoney_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(206, 206, 206)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SendMoney_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AllUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AllBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SendMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(BackToLogin_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AllUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AllBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SendMessage)
                    .addComponent(SendMoney_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(99, 99, 99)
                .addComponent(BackToLogin_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public class BookInfoPage extends JFrame {
      public BookInfoPage(Book book) {
        setTitle("Book Information");
        setSize(400, 300);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        JTextArea bookInfo = new JTextArea();
        bookInfo.setText("Title: " + book.getTitle() + "\n"
                + "Author: " + book.getAuthor() + "\n"
                + "Description: " + book.getDescription() + "\n"
                + "Status: " + (book.isAvailable() ? "free" : "taken") + "\n"
                + "Cost Per Day: " + book.getCostForDay() + "\n"
                + "Category: " + book.getCategory() + "\n"
                + "Book taken by " + book.getWhoTakeThisBook() + "\n"
                
        );
        bookInfo.setEditable(false);

        add(new JScrollPane(bookInfo));
    }
   }
    private void AllBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllBookButtonActionPerformed
           LSystem Sys = LSystem.getInstance();
           System.out.println("fsd");
        List<Integer> BookIDs = Sys.getAllBook();
        List<Book> allBooks = new ArrayList<>();
        for (Integer ID : BookIDs) {
        allBooks.add(BookProfile.GetProfile(ID));
        }

        JFrame booksFrame = new JFrame("All Books");
        booksFrame.setSize(600, 400);
        booksFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));

        for (Book book : allBooks) {
        System.out.println(book.toString());
        JPanel bookPanel = new JPanel();
        bookPanel.setLayout(new FlowLayout());

        JButton bookNameBtn = new JButton(book.getTitle());
        bookNameBtn.addActionListener(e -> {
        new BookInfoPage(book).setVisible(true);
        });

        JButton deleteBtn = new JButton("Delete");
        deleteBtn.addActionListener(e -> {
        //Sys.deleteBook(book.getId()); // Assuming there is a deleteBook function in your system
        JOptionPane.showMessageDialog(null, "Book deleted successfully!");
        booksFrame.dispose(); // Close and refresh the frame to update the list
        AllBookButtonActionPerformed(evt); // Refresh the list
        });

        bookPanel.add(bookNameBtn);
        bookPanel.add(deleteBtn);
        panel.add(bookPanel);
        }

        JScrollPane scrollPane = new JScrollPane(panel);
        booksFrame.add(scrollPane);
        booksFrame.setVisible(true);
    }//GEN-LAST:event_AllBookButtonActionPerformed

    private void AllUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllUserButtonActionPerformed
         AllUserPage allUsersPage = new AllUserPage();
    allUsersPage.setVisible(true);
    }//GEN-LAST:event_AllUserButtonActionPerformed

    private void SendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendMessageActionPerformed
        MessagePage messPage=new MessagePage();
        messPage.setVisible(true);
    }//GEN-LAST:event_SendMessageActionPerformed

    private void BackToLogin_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToLogin_ButtonActionPerformed
         new Login().setVisible(true);              
    }//GEN-LAST:event_BackToLogin_ButtonActionPerformed

    private void SendMoney_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendMoney_ButtonActionPerformed
      new SendMoneyPage().setVisible(true);
    }//GEN-LAST:event_SendMoney_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage("Ali313").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AllBookButton;
    private javax.swing.JButton AllUserButton;
    private javax.swing.JButton BackToLogin_Button;
    private javax.swing.JButton SendMessage;
    private javax.swing.JButton SendMoney_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
