/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.HashMap;
import java.util.Map;
/**
 *
 * @author Zeyad
 */
public class AllUserPage extends javax.swing.JFrame {
  private JPanel mainPanel;
    private JPanel usersPanel;
    /**
     * Creates new form AllUserPage
     */
    public AllUserPage() {
        initComponents();
        
        setTitle("All Users");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setSize(600, 400);
        
        mainPanel = new JPanel(new BorderLayout());
        usersPanel = new JPanel();
        usersPanel.setLayout(new BoxLayout(usersPanel, BoxLayout.Y_AXIS));
        
        JScrollPane scrollPane = new JScrollPane(usersPanel);
        mainPanel.add(scrollPane, BorderLayout.CENTER);
        
        refreshUserList();
        
        add(mainPanel);
        setLocationRelativeTo(null);
    }
    
    private void refreshUserList() {
        usersPanel.removeAll();
        
        // Get all users from Profile singleton
        HashMap<String, User> users;
        users.put("ali",null );
        for (User user : users.values()) {
            JPanel userPanel = createUserPanel(user);
            usersPanel.add(userPanel);
            usersPanel.add(Box.createRigidArea(new Dimension(0, 5))); // spacing between users
        }
        
        usersPanel.revalidate();
        usersPanel.repaint();
    }
    
    private JPanel createUserPanel(User user) {
        JPanel panel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        panel.setBorder(BorderFactory.createEtchedBorder());
        
        // Username label
        JLabel userLabel = new JLabel(user.getUserName());
        userLabel.setPreferredSize(new Dimension(150, 25));
        
        // Remove user button
        JButton removeButton = new JButton("Remove User");
        removeButton.addActionListener(e -> {
            int confirm = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to remove " + user.getUserName() + "?",
                "Confirm Removal",
                JOptionPane.YES_NO_OPTION
            );
            
            if (confirm == JOptionPane.YES_OPTION) {
                Profile.getInstance().removeProfile(user.getUserName());
                refreshUserList();
            }
        });
        
        // Block/Unblock button
        
        
        JButton blockButton = new JButton(user.isIsBlocked() ? "Remove from Blacklist" : "Add to Blacklist");
        blockButton.addActionListener(e -> {
            user.setIsBlocked(!user.isIsBlocked());
            refreshUserList();
        });
        
        panel.add(userLabel);
        panel.add(removeButton);
        panel.add(blockButton);
        
        return panel;
    }
    
    public void showWindow() {
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 641, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllUserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllUserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllUserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllUserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllUserPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
