/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import javax.swing.*;
import static javax.swing.JOptionPane.showMessageDialog;
/**
 *
 * @author AliRagab313
 */


public class RegisterPage extends javax.swing.JFrame {

    /**
     * Creates new form RegisterPage
     */
    public RegisterPage() {
       
        initComponents();
       this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        FirstName_txt = new javax.swing.JTextField();
        UserName_txt = new javax.swing.JTextField();
        Email_txt = new javax.swing.JTextField();
        LastName_txt = new javax.swing.JTextField();
        confirmPassword_txt = new javax.swing.JTextField();
        Password_txt = new javax.swing.JTextField();
        UserNameLable = new javax.swing.JLabel();
        EmailLable = new javax.swing.JLabel();
        FirstNameLable = new javax.swing.JLabel();
        PasswordLable = new javax.swing.JLabel();
        UserNameLable4 = new javax.swing.JLabel();
        LastNameLable = new javax.swing.JLabel();
        Register_btn = new javax.swing.JButton();
        Back_btn = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        FirstName_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstName_txtActionPerformed(evt);
            }
        });

        UserName_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserName_txtActionPerformed(evt);
            }
        });

        Email_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Email_txtActionPerformed(evt);
            }
        });

        LastName_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastName_txtActionPerformed(evt);
            }
        });

        confirmPassword_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPassword_txtActionPerformed(evt);
            }
        });

        Password_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_txtActionPerformed(evt);
            }
        });

        UserNameLable.setBackground(new java.awt.Color(0, 0, 0));
        UserNameLable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UserNameLable.setForeground(new java.awt.Color(255, 255, 255));
        UserNameLable.setLabelFor(UserName_txt);
        UserNameLable.setText("UserName");
        UserNameLable.setAutoscrolls(true);
        UserNameLable.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        EmailLable.setBackground(new java.awt.Color(0, 0, 0));
        EmailLable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EmailLable.setForeground(new java.awt.Color(255, 255, 255));
        EmailLable.setLabelFor(UserName_txt);
        EmailLable.setText("Email");
        EmailLable.setAutoscrolls(true);
        EmailLable.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        FirstNameLable.setBackground(new java.awt.Color(0, 0, 0));
        FirstNameLable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FirstNameLable.setForeground(new java.awt.Color(255, 255, 255));
        FirstNameLable.setLabelFor(FirstName_txt);
        FirstNameLable.setText("FirstName");
        FirstNameLable.setAutoscrolls(true);
        FirstNameLable.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        PasswordLable.setBackground(new java.awt.Color(0, 0, 0));
        PasswordLable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PasswordLable.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLable.setLabelFor(Password_txt);
        PasswordLable.setText("Password");
        PasswordLable.setAutoscrolls(true);
        PasswordLable.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        UserNameLable4.setBackground(new java.awt.Color(0, 0, 0));
        UserNameLable4.setForeground(new java.awt.Color(255, 255, 255));
        UserNameLable4.setLabelFor(UserName_txt);
        UserNameLable4.setText("Confirm Password");
        UserNameLable4.setAutoscrolls(true);
        UserNameLable4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        LastNameLable.setBackground(new java.awt.Color(0, 0, 0));
        LastNameLable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LastNameLable.setForeground(new java.awt.Color(255, 255, 255));
        LastNameLable.setLabelFor(LastName_txt);
        LastNameLable.setText("LastName");
        LastNameLable.setAutoscrolls(true);
        LastNameLable.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Register_btn.setText("Register");
        Register_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_btnActionPerformed(evt);
            }
        });

        Back_btn.setBackground(new java.awt.Color(153, 255, 153));
        Back_btn.setText("Back");
        Back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Register_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UserNameLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FirstNameLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LastNameLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EmailLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PasswordLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UserNameLable4, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(confirmPassword_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FirstName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LastName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Password_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UserName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Back_btn))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Back_btn)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserNameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstNameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastNameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailLable, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLable, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmPassword_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserNameLable4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Register_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FirstName_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstName_txtActionPerformed
      
       
    }//GEN-LAST:event_FirstName_txtActionPerformed

    private void UserName_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserName_txtActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_UserName_txtActionPerformed

    private void Email_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Email_txtActionPerformed

    private void LastName_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastName_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastName_txtActionPerformed

    private void confirmPassword_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPassword_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPassword_txtActionPerformed

    private void Password_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password_txtActionPerformed

    private void Register_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_btnActionPerformed
        if(!Validation.CheckField(FirstName_txt.getText())||!Validation.CheckField(LastName_txt.getText())||!Validation.CheckField(UserName_txt.getText())) 
        {
                JOptionPane.showMessageDialog(null, "Empty Field");      
                return ;
        }
        System.out.println("1");
        
        if(!Validation.CheckEmail(Email_txt.getText()))
        {
               
                JOptionPane.showMessageDialog(null, "Email not correct");      
                return ;
        }
        System.out.println("2");
        if(!Validation.CheckPassword(Password_txt.getText()))
        {
                
                JOptionPane.showMessageDialog(null, "Password will be must at least 3 characters");      
                return;
        }
        System.out.println("3");
        DataBase DB=DataBase.getInstance();
        if(DB.checkUserNameFound(UserName_txt.getText()))
        {
               JOptionPane.showMessageDialog(null, "UserName is already used");                     
               return;
        }
        System.out.println("4");
        if(DB.checkEmailFound(Email_txt.getText()))
        {
               JOptionPane.showMessageDialog(null, "Email is already used");      
               
               return;
        }
        System.out.println("5");
        if(!Password_txt.getText().equals(confirmPassword_txt.getText()))
        {
                  JOptionPane.showMessageDialog(null, "Password Not Match");                     
               return;
        }
        System.out.println("6");
        DB.insertUser(UserName_txt.getText(),Password_txt.getText(), FirstName_txt.getText(), LastName_txt.getText(), Email_txt.getText(),1000.0, false, false);
        new HomePage(UserName_txt.getText()).setVisible(true);            
        this.setVisible(false);
        System.out.println("7");
    }//GEN-LAST:event_Register_btnActionPerformed

    private void Back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_btnActionPerformed
        // TODO add your handling code here:
         new Login().setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_Back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_btn;
    private javax.swing.JLabel EmailLable;
    private javax.swing.JTextField Email_txt;
    private javax.swing.JLabel FirstNameLable;
    private javax.swing.JTextField FirstName_txt;
    private javax.swing.JLabel LastNameLable;
    private javax.swing.JTextField LastName_txt;
    private javax.swing.JLabel PasswordLable;
    private javax.swing.JTextField Password_txt;
    private javax.swing.JButton Register_btn;
    private javax.swing.JLabel UserNameLable;
    private javax.swing.JLabel UserNameLable4;
    private javax.swing.JTextField UserName_txt;
    private javax.swing.JTextField confirmPassword_txt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
